export const FETCH_STARWAR_CATEGORIES = "FETCH_STARWAR_CATEGORIES";
export const STARWAR_DATA_LOADING = "STARWAR_DATA_LOADING";
export const STARWAR_LOADING_SUCCESS = "STARWAR_LOADING_SUCCESS";
export const STARWAR_LOADING_ERROR = "STARWAR_LOADING_ERROR";
export const FETCH_STARWAR_DATA = "FETCH_STARWAR_DATA";
export const FETCH_STARWAR_DATA_SUCCESS = "FETCH_STARWAR_DATA_SUCCESS";
export const STARWAR_CONTENT_LOADING = "STARWAR_CONTENT_LOADING";
